### ISSUE TITLE
GeoJSON format not valid

### ISSUE THREAD

**Issue by igortme** [wavecomtech/ccfiw#2]
Hemos detectado que está generando un error el formato en el que se envía el campo location (ocurrirá igual con otros de tipo geo:json si los hay), concretamente devuelve este error:
 
JSON Parse Error in ContextAttribute::Object (geo:json needs an object or null as value)
 
El formato en el que está llegando la información de este atributo ahora mismo es así:
 
```
"location":{"value":["-3.364221","40.48307"],"type":"geo:json"},
```
o 
```
["-3.364221","40.48307"]
```
Y sin embargo debería llegar así:
 
```
{
  "type": "Point",
  "coordinates": [
    -3.364221,
    40.48307
  ]
}
```

¿Podéis modificar el formato en aquellos que sean del mismo tipo por favor?

**Comment by TFM93** [comment]
Hi Igor, 
the commit [https://github.com/wavecomtech/ccfiw/commit/5f0c613f235864dceb2ffad4e029ce588d4b8a4b](url) should fix this issue. 
Please check 👍

**Comment by TFM93** [comment]
Hi @igortme ,
the commit 5f0c613 should fix this.
Please check 👍
